# Generated by Django 5.1.1 on 2024-09-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='is_on_vacation',
            field=models.BooleanField(default=False),
        ),
    ]
